/**
 * Scans public/cases/ and generates components/cases.ts
 *
 * Each subfolder = one category (filter).
 * Each file (PDF / JPG / PNG) = one case item.
 * Sub-subfolders inside categories (e.g. "презентация СПФ") are merged into
 * a single "gallery" case that contains every image from that subfolder.
 */

import { readdir, stat, writeFile, mkdir } from "node:fs/promises";
import { join, extname, basename } from "node:path";

const ROOT = join(process.cwd(), "public", "cases");
const OUT = join(process.cwd(), "components", "cases.ts");

const IMAGE_EXTS = new Set([".jpg", ".jpeg", ".png", ".webp"]);
const PDF_EXTS = new Set([".pdf"]);

async function scan(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const out = [];

  for (const e of entries) {
    if (e.name.startsWith(".") || e.name === ".DS_Store") continue;

    const full = join(dir, e.name);
    if (e.isDirectory()) {
      // Recurse into subfolder and return its files as a gallery
      const sub = await scan(full);
      if (sub.length > 0) {
        out.push({ name: e.name, files: sub, isGallery: true });
      }
    } else {
      out.push({ name: e.name, isGallery: false });
    }
  }

  return out;
}

function cleanTitle(filename) {
  return basename(filename, extname(filename))
    .replace(/[_-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

async function main() {
  const categories = await scan(ROOT);
  const cases = [];
  let id = 1;

  for (const cat of categories) {
    if (cat.isGallery) {
      // We are listing the ROOT — cat here is actually a category folder content
      // This branch shouldn't be hit at top level, handle below
      continue;
    }
  }

  // Actually walk subdirectories of ROOT (each = category)
  const topEntries = await readdir(ROOT, { withFileTypes: true });

  for (const catEntry of topEntries) {
    if (!catEntry.isDirectory()) continue;
    if (catEntry.name.startsWith(".")) continue;

    const catPath = join(ROOT, catEntry.name);
    const catFiles = await scan(catPath);

    // Separate top-level PDFs/images and subfolder galleries
    const directFiles = [];
    const subGalleries = [];

    for (const f of catFiles) {
      if (f.isGallery) subGalleries.push(f);
      else directFiles.push(f);
    }

    // Each direct file = one case
    for (const f of directFiles) {
      const ext = extname(f.name).toLowerCase();
      const isPdf = PDF_EXTS.has(ext);
      const isImg = IMAGE_EXTS.has(ext);

      if (!isPdf && !isImg) continue;

      cases.push({
        id: String(id++).padStart(3, "0"),
        type: isPdf ? "pdf" : "image",
        title: cleanTitle(f.name),
        category: catEntry.name.trim(),
        media: `/cases/${encodeURIComponent(catEntry.name)}/${encodeURIComponent(f.name)}`,
        thumb: isImg
          ? `/cases/${encodeURIComponent(catEntry.name)}/${encodeURIComponent(f.name)}`
          : undefined,
      });
    }

    // Each subfolder = one gallery case
    for (const gallery of subGalleries) {
      const imgs = gallery.files
        .filter((f) => IMAGE_EXTS.has(extname(f.name).toLowerCase()))
        .sort();
      const pdfs = gallery.files.filter((f) =>
        PDF_EXTS.has(extname(f.name).toLowerCase())
      );

      if (imgs.length === 0 && pdfs.length === 0) continue;

      const mediaFile = imgs[0] || pdfs[0];
      const ext = extname(mediaFile.name).toLowerCase();
      const isPdf = PDF_EXTS.has(ext);

      cases.push({
        id: String(id++).padStart(3, "0"),
        type: imgs.length > 1 ? "gallery" : isPdf ? "pdf" : "image",
        title: cleanTitle(gallery.name),
        category: catEntry.name.trim(),
        media: `/cases/${encodeURIComponent(catEntry.name)}/${encodeURIComponent(gallery.name)}/${encodeURIComponent(mediaFile.name)}`,
        thumb: !isPdf
          ? `/cases/${encodeURIComponent(catEntry.name)}/${encodeURIComponent(gallery.name)}/${encodeURIComponent(mediaFile.name)}`
          : undefined,
        ...(imgs.length > 1 && {
          gallery: imgs.map(
            (f) =>
              `/cases/${encodeURIComponent(catEntry.name)}/${encodeURIComponent(gallery.name)}/${encodeURIComponent(f.name)}`
          ),
        }),
      });
    }
  }

  // Generate TypeScript file
  const typeDef = `// Auto-generated by scripts/build-cases.mjs — DO NOT EDIT\n// Run: node scripts/build-cases.mjs\n\nexport type CaseType = "pdf" | "image" | "gallery";\n\nexport interface CaseItem {\n  id: string;\n  type: CaseType;\n  title: string;\n  category: string;\n  media: string;           // URL to main file\n  thumb?: string;          // URL to thumbnail (for PDFs: rendered via PdfThumb)\n  gallery?: string[];      // for type="gallery": all image URLs\n}`;
  const data = `export const cases: CaseItem[] = ${JSON.stringify(cases, null, 2)};\n`;

  await writeFile(OUT, `${typeDef}\n\n${data}`);
  console.log(`✓ Generated ${cases.length} cases → ${OUT}`);
  console.log(`  Categories: ${[...new Set(cases.map((c) => c.category))].join(", ")}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
